# Generated by Django 3.0 on 2020-09-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200928_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follwing',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
