# Generated by Django 3.0 on 2020-09-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follwing',
            new_name='following',
        ),
    ]
